makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-slate
include:
  - assets
  - README.md
exclude:
  - pics
  - node_modules
  - pxt_modules
  - built
  - tools
  - .slim
  - _history
