/**
 * Custom blocks
 */
//% weight=100 color=#0fbc11 icon="\uf0c3"
namespace halloween {
    // Auto-generated sprite functions from XCF files
    // Generated by convert_all_sprites.py

    //% block
    export function Falsch(): number[][] {
        return [
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7]
        ]
    }

    //% block
    export function Geist(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    //% block
    export function Herz(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    //% block
    export function Kürbis(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(51, 104, 0), 13], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5],
            [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    //% block
    export function OK(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    //% block
    export function Totenkopf(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    //% block
    export function Zuckerstange(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }
}
