/**
 * Custom blocks
 */
//% weight=100 color=#0fbc11 icon="\uf0c3"
namespace halloween {
    // Auto-generated sprite functions from XCF files
    // Generated by convert_all_sprites.py

    //% blockId="stevens_law_brightness"
    //% block="perceived brightness of %inputValue|with exponent %exponent"
    //% help="Applies Stevens' Power Law to correct brightness perception. Use smaller exponents (<1) for brighter midtones, larger (>1) for darker response."
    //% group="Effects"
    //% inlineInputMode=inline
    //% weight=85
    //% inputValue.min=0 inputValue.max=255 inputValue.defl=128
    //% exponent.defl=1.0
    export function stevensLawBrightness(inputValue: number, exponent: number = 1.0): number {
        // Clamp input to 0..255
        const clamped = Math.max(0, Math.min(255, inputValue))

        // Normalize to 0..1
        const normalized = clamped / 255

        // Apply Stevens' Power Law
        const perceived = Math.pow(normalized, exponent)

        // Scale back to 0..255 (integer)
        return Math.round(perceived * 255)
    }

    // Helper: clamp to 0..255
    function clamp8(n: number) {
        return Math.max(0, Math.min(255, n | 0))
    }

    // Helper: scale a 24-bit RGB color by a factor (0..255)
    function scaleColor24(c: number, factor: number) {
        const r = (c >> 16) & 0xFF
        const g = (c >> 8) & 0xFF
        const b = c & 0xFF
        const rr = Math.idiv(r * factor, 255)
        const gg = Math.idiv(g * factor, 255)
        const bb = Math.idiv(b * factor, 255)
        return (rr << 16) | (gg << 8) | bb
    }

    /**
     * Display a 5×5 RGBW image on a NeoPixel strip with independent RGB/White brightness,
     * optional clear before drawing, and optional auto-show.
     * @param strip The NeoPixel strip or matrix to draw on
     * @param RGBW The 25-element image array: [ [neopixel.rgb(r,g,b), w], ... ]
     * @param brightnessRGB Brightness for RGB (0–255). Default 255
     * @param brightnessW Brightness for White (0–255). Default 255
     * @param showAfter Call show() after drawing (default true)
     */
    //% blockId="bild_anzeigen_advanced"
    //% block="display %RGBW on %strip|RGB %brightnessRGB|White %brightnessW|show %showAfter"
    //% group="Display"
    //% inlineInputMode=inline
    //% weight=100
    //% brightnessRGB.min=0 brightnessRGB.max=255 brightnessRGB.defl=255
    //% brightnessW.min=0 brightnessW.max=255 brightnessW.defl=255
    export function Bild_anzeigen(
        RGBW: number[][],
        strip: neopixel.Strip,
        brightnessRGB: number = 255,
        brightnessW: number = 255,
        showAfter: boolean = true
    ) {
        const br = clamp8(brightnessRGB)
        const bw = clamp8(brightnessW)

        for (let i = 0; i < 25 && i < RGBW.length; i++) {
            const c = RGBW[i][0] | 0
            const w = clamp8(RGBW[i][1] || 0)
            const cScaled = (br === 255) ? c : scaleColor24(c, br)
            const wScaled = (bw === 255) ? w : Math.idiv(w * bw, 255)
            strip.setPixelColor(i, cScaled)
            strip.setPixelWhiteLED(i, wScaled)
        }

        if (showAfter) strip.show()
    }

    /**
     * Calculates a pulsing brightness value (0–255) based on the system time.
     * @param cycleMs Full pulse cycle time in milliseconds (e.g. 2000 = 2 s up/down)
     * @param minB Minimum brightness (0–255)
     * @param maxB Maximum brightness (0–255)
     * @returns Brightness value (0–255)
     */
    //% blockId="pulsing_brightness"
    //% block="pulsing brightness with cycle %cycleMs|ms min %minB|max %maxB"
    //% help="Generates a sinusoidal brightness between min and max based on the system millisecond tick."
    //% group="Effects"
    //% inlineInputMode=inline
    //% weight=90
    //% cycleMs.defl=2000 minB.defl=50 maxB.defl=255
    export function Pulsing_Brightness(cycleMs: number, minB: number, maxB: number): number {
        const now = control.millis() % cycleMs
        const phase = (now / cycleMs) * 2 * Math.PI
        const wave = (Math.sin(phase) + 1) / 2  // 0..1
        const value = minB + wave * (maxB - minB)
        return Math.round(value)
    }

    // Auto-generated sprite functions from XCF files
    // Generated by convert_all_sprites.py

    /**
    * Returns the 5×5 RGBW sprite for Falsch.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Falsch"
    //% block="Falsch image"
    //% help="Provides the 5×5 Falsch image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Falsch(): number[][] {
        return [
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Geist.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Geist"
    //% block="Geist image"
    //% help="Provides the 5×5 Geist image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Geist(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Herz.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Herz"
    //% block="Herz image"
    //% help="Provides the 5×5 Herz image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Herz(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(248, 0, 8), 7], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Kürbis.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Kürbis"
    //% block="Kürbis image"
    //% help="Provides the 5×5 Kürbis image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Kürbis(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(51, 104, 0), 13], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(67, 31, 0), 183], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(67, 31, 0), 183], [neopixel.rgb(245, 116, 0), 5],
            [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(67, 31, 0), 183], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(245, 116, 0), 5], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for OK.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_OK"
    //% block="OK image"
    //% help="Provides the 5×5 OK image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function OK(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 255, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Totenkopf.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Totenkopf"
    //% block="Totenkopf image"
    //% help="Provides the 5×5 Totenkopf image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Totenkopf(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Zuckerstange.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Zuckerstange"
    //% block="Zuckerstange image"
    //% help="Provides the 5×5 Zuckerstange image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Zuckerstange(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0]
        ]
    }

    /**
    * Returns the 5×5 RGBW sprite for Zuckerstange2.
    * Each element is [ [neopixel.rgb(r,g,b), whiteBrightness] ].
    */
    //% blockId="sprite_Zuckerstange2"
    //% block="Zuckerstange2 image"
    //% help="Provides the 5×5 Zuckerstange2 image as an RGBW array for display on your NeoPixel matrix."
    //% group="Images"
    //% weight=100
    export function Zuckerstange2(): number[][] {
        return [
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 0],
            [neopixel.rgb(0, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(255, 0, 0), 0], [neopixel.rgb(0, 0, 0), 255], [neopixel.rgb(0, 0, 0), 0]
        ]
    }
}
